//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from IdentifierGrammar.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="IdentifierGrammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IIdentifierGrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdentifierGrammarParser.z"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterZ([NotNull] IdentifierGrammarParser.ZContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdentifierGrammarParser.z"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitZ([NotNull] IdentifierGrammarParser.ZContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdentifierGrammarParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] IdentifierGrammarParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdentifierGrammarParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] IdentifierGrammarParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdentifierGrammarParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] IdentifierGrammarParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdentifierGrammarParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] IdentifierGrammarParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdentifierGrammarParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] IdentifierGrammarParser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdentifierGrammarParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] IdentifierGrammarParser.StringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IdentifierGrammarParser.symbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSymbol([NotNull] IdentifierGrammarParser.SymbolContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IdentifierGrammarParser.symbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSymbol([NotNull] IdentifierGrammarParser.SymbolContext context);
}
